import { Padding } from "@mui/icons-material"
import './globals.css'; // Adjust the path if needed

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body sx={{padding: 0}}>{children}</body>
    </html>
  )
}
